AVSHighSchool/AVSWebMvc/Controllers/GallaryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.IO;
using System.Web.Mvc;
using AVSWebMvc.Models.DB;

namespace AVSWebMvc.Controllers
{
    public class GallaryController : Controller
    {
        private AVSSchoolEntities db = new AVSSchoolEntities();

        //
        // GET: /Gallary/

        public ActionResult Index()
        {
            var ms_gallary = db.MS_GALLARY.Where(s => s.RES_STATUS == "A");
            foreach (var itm in ms_gallary)
            {
                itm.GAL_IMAGE = "/Files/Gallary/" + itm.GAL_IMAGE;
            }
            return View(ms_gallary.ToList());
        }

        //
        // GET: /Gallary/Details/5

        public ActionResult Details(int id)
        {
            MS_GALLARY ms_gallary = db.MS_GALLARY.Single(m => m.GAL_ID == id);
            ms_gallary.GAL_IMAGE = "/Files/Gallary/" + ms_gallary.GAL_IMAGE;
            if (ms_gallary == null)
            {
                return HttpNotFound();
            }
            return View(ms_gallary);
        }

        //
        // GET: /Gallary/Create

        public ActionResult Create()
        {
            if (Session["user"] != null)
            {
                if (Session["user"].ToString() == "AVS")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        //
        // POST: /Gallary/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MS_GALLARY ms_gallary, HttpPostedFileBase ImageFile)
        {
            if (Session["user"] != null)
            {
                if (Session["user"].ToString() == "AVS")
            {
                if (ModelState.IsValid)
                {
                    ms_gallary.GAL_ID = db.MS_GALLARY.Any() ? (db.MS_GALLARY.Max(S => S.GAL_ID)) + 1 : 1;
                    string filename = Path.GetFileNameWithoutExtension(ImageFile.FileName);
                    string extension = Path.GetExtension(ImageFile.FileName);
                    filename = filename + extension;
                    filename = "GAL" + ms_gallary.GAL_ID + extension;
                    ms_gallary.GAL_IMAGE = filename;
                    filename = Path.Combine(Server.MapPath("~/Files/Gallary/"), filename);
                    ImageFile.SaveAs(filename);
                    ms_gallary.RES_STATUS = "A";
                    db.MS_GALLARY.Add(ms_gallary);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            return View(ms_gallary);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        //
        // GET: /Gallary/Edit/5

        public ActionResult Edit(int id)
        {
            if (Session["user"] != null)
            {
                if (Session["user"].ToString() == "AVS")
            {
                MS_GALLARY ms_gallary = db.MS_GALLARY.Single(m => m.GAL_ID == id);
                ms_gallary.GAL_IMAGE = "/Files/Gallary/" + ms_gallary.GAL_IMAGE;
                if (ms_gallary == null)
            {
                return HttpNotFound();
            }
            return View(ms_gallary);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        //
        // POST: /Gallary/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MS_GALLARY ms_gallary, HttpPostedFileBase ImageFile)
        {
            MS_GALLARY us_mast_gallary = db.MS_GALLARY.FirstOrDefault(s => s.GAL_ID == ms_gallary.GAL_ID);
            if (Session["user"] != null)
            {
                if (Session["user"].ToString() == "AVS")
            {
                if (ModelState.IsValid)
            {
                    if (ImageFile != null)
                    {
                        string filename = Path.GetFileNameWithoutExtension(ImageFile.FileName);
                        string extension = Path.GetExtension(ImageFile.FileName);
                        filename = filename + extension;
                        filename = "GAL" + ms_gallary.GAL_ID + extension;
                        ms_gallary.GAL_IMAGE = filename;
                        filename = Path.Combine(Server.MapPath("~/Files/Gallary/"), filename);
                        ImageFile.SaveAs(filename);
                        us_mast_gallary.GAL_IMAGE = ms_gallary.GAL_IMAGE;
                    }
                     us_mast_gallary.DESCRIP = ms_gallary.DESCRIP;
                    
                    //db.MS_GALLARY.Attach(ms_gallary);
                //db.ObjectStateManager.ChangeObjectState(ms_gallary, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ms_gallary);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        //
        // GET: /Gallary/Delete/5

        public ActionResult Delete(int id)
        {
            if (Session["user"] != null)
            {
                if (Session["user"].ToString() == "AVS")
            {
                MS_GALLARY ms_gallary = db.MS_GALLARY.Single(m => m.GAL_ID == id);
                ms_gallary.GAL_IMAGE = "/Files/Gallary/" + ms_gallary.GAL_IMAGE;
                if (ms_gallary == null)
            {
                return HttpNotFound();
            }
            return View(ms_gallary);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        //
        // POST: /Gallary/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["user"] != null)
            {
                if (Session["user"].ToString() == "AVS")
            {
                MS_GALLARY ms_gallary = db.MS_GALLARY.Single(m => m.GAL_ID == id);
                ms_gallary.RES_STATUS = "D";
                // db.MS_GALLARY.DeleteObject(ms_gallary);
                db.SaveChanges();
            return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

AVSHighSchool/AVSWebMvc/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.IO;
using System.Web.Mvc;
using AVSWebMvc.Models.DB;

namespace AVSWebMvc.Controllers
{
    public class NewsController : Controller
    {
        private AVSSchoolEntities db = new AVSSchoolEntities();

        //
        // GET: /News/

        public ActionResult Index()
        {
            try
            {
                var ms_news = db.MS_NEWS.Where(s=>s.RES_STATUS == "A");
                foreach(var itm in ms_news)
                {
                    itm.NEWS_IMAGE = "/Files/News/" + itm.NEWS_IMAGE;
                }
                return View(ms_news.ToList());
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        //
        // GET: /News/Details/5

        public ActionResult Details(int id)
        {

            MS_NEWS ms_news = db.MS_NEWS.Single(m => m.NEWS_ID == id);
            ms_news.NEWS_IMAGE = "/Files/News/" + ms_news.NEWS_IMAGE;
            if (ms_news == null)
            {
                return HttpNotFound();
            }
            return View(ms_news);
        }

        //
        // GET: /News/Create

        public ActionResult Create()
        {
            if (Session["user"] != null)
            {
                if (Session["user"].ToString() == "AVS")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        //
        // POST: /News/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MS_NEWS ms_news, HttpPostedFileBase ImageFile)
        {
            if (Session["user"] != null)
            {
                if (Session["user"].ToString() == "AVS")
            {
                if (ModelState.IsValid)
            {
                    ms_news.NEWS_ID = db.MS_NEWS.Any() ? (db.MS_NEWS.Max(S => S.NEWS_ID)) + 1 : 1;
                    string filename = Path.GetFileNameWithoutExtension(ImageFile.FileName);
                    string extension = Path.GetExtension(ImageFile.FileName);
                    filename = filename + extension;
                    filename = "NEWS" + ms_news.NEWS_ID + extension;
                    ms_news.NEWS_IMAGE = filename;
                    filename = Path.Combine(Server.MapPath("~/Files/News/"), filename);
                    ImageFile.SaveAs(filename);
                    ms_news.RES_STATUS = "A";
                    db.MS_NEWS.Add(ms_news);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ms_news);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        //
        // GET: /News/Edit/5

        public ActionResult Edit(int id)
        {
            if (Session["user"] != null)
            {
                if (Session["user"].ToString() == "AVS")
            {
                MS_NEWS ms_news = db.MS_NEWS.Single(m => m.NEWS_ID == id);
                ms_news.NEWS_IMAGE = "/Files/News/" + ms_news.NEWS_IMAGE;
                if (ms_news == null)
            {
                return HttpNotFound();
            }
            return View(ms_news);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        //
        // POST: /News/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MS_NEWS ms_news, HttpPostedFileBase ImageFile)
        {
            MS_NEWS us_mast_news = db.MS_NEWS.FirstOrDefault(s=>s.NEWS_ID == ms_news.NEWS_ID);
            if (Session["user"] != null)
            {
                if (Session["user"].ToString() == "AVS")
            {
                
                if (ModelState.IsValid)
            {
                    
                    if (ImageFile != null)
                    {
                        string filename = Path.GetFileNameWithoutExtension(ImageFile.FileName);
                        string extension = Path.GetExtension(ImageFile.FileName);
                        filename = filename + extension;
                        filename = "NEWS" + ms_news.NEWS_ID + extension;
                        ms_news.NEWS_IMAGE = filename;
                        filename = Path.Combine(Server.MapPath("~/Files/News/"), filename);
                        ImageFile.SaveAs(filename);
                        us_mast_news.NEWS_IMAGE = ms_news.NEWS_IMAGE;
                    }
                    //db.MS_NEWS.Attach(ms_news);
                    us_mast_news.TITLE = ms_news.TITLE;
                    us_mast_news.NEWS_DATE = ms_news.NEWS_DATE;
                    us_mast_news.DESCRIP = ms_news.DESCRIP;

                    db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ms_news);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        //
        // GET: /News/Delete/5

        public ActionResult Delete(int id)
        {
            if (Session["user"] != null)
            {
                if (Session["user"].ToString() == "AVS")
            {
                MS_NEWS ms_news = db.MS_NEWS.Single(m => m.NEWS_ID == id);
                ms_news.NEWS_IMAGE = "/Files/News/" + ms_news.NEWS_IMAGE;
                if (ms_news == null)
            {
                return HttpNotFound();
            }
            return View(ms_news);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        //
        // POST: /News/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["user"] != null)
            {
                if (Session["user"].ToString() == "AVS")
            {
                MS_NEWS ms_news = db.MS_NEWS.Single(m => m.NEWS_ID == id);
            ms_news.RES_STATUS = "D";
            //db.MS_NEWS.DeleteObject(ms_news);
            db.SaveChanges();
            return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

AVSHighSchool/AVSWebMvc/Views/_LayoutPage1.cshtml
<!DOCTYPE html>

<html>
<head>
	<title>AVS High School | Higher Secondary School in Puliyangudi, Thirunelveli</title>
	<!--/tags -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="AVS High School" />
	<script type="application/x-javascript">
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<!--//tags -->
	<link href="../../css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
	<link href="../../css/style.css" rel="stylesheet" type="text/css" media="all" />
	<link rel="stylesheet" href="../../css/owl.carousel.css" type="text/css" media="all">
	<link rel="stylesheet" href="../../css/owl.theme.css" type="text/css" media="all">
	<link href="../../css/font-awesome.css" rel="stylesheet">
	<!-- //for bootstrap working -->
	<link href="//fonts.googleapis.com/css?family=Work+Sans:200,300,400,500,600,700" rel="stylesheet">

		<script type="text/javascript" src="../../js/jquery-2.1.4.min.js"></script>

</head>
<body>
<!-- header -->
	<div class="header">
	<div class="agileits_top_menu">
		<div class="w3l_header_left">
				<ul>
					<li><i class="fa fa-phone" aria-hidden="true"></i> +91 99425 71395</li>
					<li><i class="fa fa-envelope-o" aria-hidden="true"></i> <a href="mailto:info@example.com">info@avshighschool.com</a></li>
				</ul>
			</div>
			<div class="w3l_header_right">
				<div class="w3ls-social-icons text-left">
					<a class="facebook" href="#"><i class="fa fa-facebook"></i></a>
					<a class="twitter" href="#"><i class="fa fa-twitter"></i></a>
					<a class="pinterest" href="#"><i class="fa fa-pinterest-p"></i></a>
					<a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a>
				</div>
			</div>
			<div class="clearfix"> </div>
		</div>
		<div class="content white agile-info">
			<nav class="navbar navbar-default" role="navigation">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
						<a class="navbar-brand" href="@Url.Action("Index", "Home")">
							<h1><span class="fa fa-book" aria-hidden="true"></span> AVS HIGH SCHOOL <label>Education</label></h1>
						</a>
					</div>
					<!--/.navbar-header-->
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<nav class="link-effect-2" id="link-effect-2">
							<ul class="nav navbar-nav">
								@*<li class="active"><a href="index.html" class="effect-3">Home</a></li>
								<li><a href="about.html" class="effect-3">About</a></li>
								<li><a href="services.html" class="effect-3">Services</a></li>
								<li><a href="gallery.html" class="effect-3">Gallery</a></li>
								<li class="dropdown">
									<a href="#" class="dropdown-toggle effect-3" data-toggle="dropdown">Pages <b class="caret"></b></a>
									<ul class="dropdown-menu">
										<li><a href="codes.html">Codes</a></li>
										<li><a href="icons.html">Icons</a></li>
									</ul>
								</li>
								<li><a href="contact.html" class="effect-3">Contact</a></li>*@
                                <li><a href="@Url.Action("Result", "Home")" class="effect-3">Result 2019</a></li>
							</ul>
						</nav>
					</div>
					<!--/.navbar-collapse-->
					<!--/.navbar-->
				</div>
			</nav>
		</div>
	</div>
    <div>

        @RenderBody()
    </div>

    <!-- footer -->
	<div class="footer_top_agileits">
		<div class="container">
			<div class="col-md-4 footer_grid">
				<h3>About Us</h3>
				<p>Nam libero tempore cum vulputate id est id, pretium semper enim. Morbi viverra congue nisi vel pulvinar posuere sapien
					eros.
				</p>
			</div>
			<div class="col-md-4 footer_grid">
				<h3>Latest News</h3>
				<ul class="footer_grid_list">
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="#" data-toggle="modal" data-target="#myModal">Lorem ipsum neque vulputate </a>
					</li>
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="#" data-toggle="modal" data-target="#myModal">Dolor amet sed quam vitae</a>
					</li>
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="#" data-toggle="modal" data-target="#myModal">Lorem ipsum neque, vulputate </a>
					</li>
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="#" data-toggle="modal" data-target="#myModal">Dolor amet sed quam vitae</a>
					</li>
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="#" data-toggle="modal" data-target="#myModal">Lorem ipsum neque, vulputate </a>
					</li>
				</ul>
			</div>
			<div class="col-md-4 footer_grid">
				<h3>Contact Info</h3>
				<ul class="address">
					<li><i class="fa fa-map-marker" aria-hidden="true"></i>8088 USA, Honey block, <span>New York City.</span></li>
					<li><i class="fa fa-envelope" aria-hidden="true"></i><a href="mailto:info@example.com">info@example.com</a></li>
					<li><i class="fa fa-phone" aria-hidden="true"></i>+09187 8088 9436</li>
				</ul>
			</div>
			<div class="clearfix"> </div>
			<div class="footer_grids">
				<div class="col-md-4 footer_grid_left">
					<h3>Sign up for our Newsletter</h3>
				</div>
				<div class="col-md-8 footer_grid_right">

					<form action="#" method="post">
						<input type="email" name="Email" placeholder="Enter Email Address..." required="">
						<input type="submit" value="Submit">
					</form>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<div class="footer_w3ls">
		<div class="container">
					<div class="footer_bottom1">
						<p>© 2018 Instruction. All rights reserved | Design by <a href="http://w3layouts.com">W3layouts</a></p>
					</div>
		</div>
	</div>
	<!-- //footer -->

    <a href="#home" class="scroll" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
	<!-- js -->
	
	<script type="text/javascript" src="../../js/bootstrap.js"></script>
	<!-- stats -->
	<script src="../../js/jquery.waypoints.min.js"></script>
	<script src="../../js/jquery.countup.js"></script>
	<script>
	    $('.counter').countUp();
	</script>
	<!-- //stats -->
	<!-- owl carousel -->
	<script src="../../js/owl.carousel.js"></script>
	<script>
	    $(document).ready(function () {
	        $("#owl-demo").owlCarousel({

	            autoPlay: 3000, //Set AutoPlay to 3 seconds
	            autoPlay: true,
	            items: 3,
	            itemsDesktop: [991, 2],
	            itemsDesktopSmall: [414, 4]

	        });
	    }); 
	</script>
	<!-- //owl carousel -->

</body>
</html>

AVSHighSchool/AVSWebMvc/Views/_LayoutPage2.cshtml
<!DOCTYPE html>

<html>
<head>
	<title>AVS High School | Higher Secondary School in Puliyangudi, Thirunelveli</title>
	<!--/tags -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="AVS High School" />
	<script type="application/x-javascript">
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<!--//tags -->
	<link href="../../css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
	<link href="../../css/style.css" rel="stylesheet" type="text/css" media="all" />
	<link rel="stylesheet" href="../../css/owl.carousel.css" type="text/css" media="all">
	<link rel="stylesheet" href="../../css/owl.theme.css" type="text/css" media="all">
	<link href="../../css/font-awesome.css" rel="stylesheet">
	<!-- //for bootstrap working -->
	<link href="//fonts.googleapis.com/css?family=Work+Sans:200,300,400,500,600,700" rel="stylesheet">

		<script type="text/javascript" src="../../js/jquery-2.1.4.min.js"></script>

</head>
<body>
<!-- header -->
	<div class="header">
	<div class="agileits_top_menu">
		<div class="w3l_header_left">
				<ul>
					<li><i class="fa fa-phone" aria-hidden="true"></i> +91 99425 71395</li>
					<li><i class="fa fa-envelope-o" aria-hidden="true"></i> <a href="mailto:info@example.com">info@avshighschool.com</a></li>
				</ul>
			</div>
			<div class="w3l_header_right">
				<div class="w3ls-social-icons text-left">
					<a class="facebook" href="#"><i class="fa fa-facebook"></i></a>
					<a class="twitter" href="#"><i class="fa fa-twitter"></i></a>
					<a class="pinterest" href="#"><i class="fa fa-pinterest-p"></i></a>
					<a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a>
				</div>
			</div>
			<div class="clearfix"> </div>
		</div>
		<div class="content white agile-info">
			<nav class="navbar navbar-default" role="navigation">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
						<a class="navbar-brand" href="@Url.Action("Index", "Home")">
							<h1><span class="fa fa-book" aria-hidden="true"></span> AVS HIGH SCHOOL <label>Education</label></h1>
						</a>
					</div>
					<!--/.navbar-header-->
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<nav class="link-effect-2" id="link-effect-2">
                            <ul class="nav navbar-nav">
                                @*<li class="active"><a href="index.html" class="effect-3">Home</a></li>
        <li><a href="about.html" class="effect-3">About</a></li>
        <li><a href="services.html" class="effect-3">Services</a></li>
        <li><a href="gallery.html" class="effect-3">Gallery</a></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle effect-3" data-toggle="dropdown">Pages <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><a href="codes.html">Codes</a></li>
                <li><a href="icons.html">Icons</a></li>
            </ul>
        </li>
        <li><a href="contact.html" class="effect-3">Contact</a></li>*@
                                <li><a href="@Url.Action("AdminPortal", "Home")" class="effect-3">Publish Result</a></li>
                                <li><a href="@Url.Action("Index", "News")" class="effect-3">News</a></li>
                                <li><a href="@Url.Action("Index", "Gallary")" class="effect-3">Gallary</a></li>
                                <li><a href="@Url.Action("Index", "SchoolTopper")" class="effect-3">School Topper</a></li>
                                <li><a href="@Url.Action("Logout", "Home")" class="effect-3">Logout</a></li>
                            </ul>
						</nav>
					</div>
					<!--/.navbar-collapse-->
					<!--/.navbar-->
				</div>
			</nav>
		</div>
	</div>
    <div>

        @RenderBody()
    </div>

    <!-- footer -->
	<div class="footer_top_agileits">
		<div class="container">
			<div class="col-md-4 footer_grid">
				<h3>About Us</h3>
				<p>Nam libero tempore cum vulputate id est id, pretium semper enim. Morbi viverra congue nisi vel pulvinar posuere sapien
					eros.
				</p>
			</div>
			<div class="col-md-4 footer_grid">
				<h3>Latest News</h3>
				<ul class="footer_grid_list">
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="#" data-toggle="modal" data-target="#myModal">Lorem ipsum neque vulputate </a>
					</li>
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="#" data-toggle="modal" data-target="#myModal">Dolor amet sed quam vitae</a>
					</li>
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="#" data-toggle="modal" data-target="#myModal">Lorem ipsum neque, vulputate </a>
					</li>
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="#" data-toggle="modal" data-target="#myModal">Dolor amet sed quam vitae</a>
					</li>
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="#" data-toggle="modal" data-target="#myModal">Lorem ipsum neque, vulputate </a>
					</li>
				</ul>
			</div>
			<div class="col-md-4 footer_grid">
				<h3>Contact Info</h3>
				<ul class="address">
					<li><i class="fa fa-map-marker" aria-hidden="true"></i>8088 USA, Honey block, <span>New York City.</span></li>
					<li><i class="fa fa-envelope" aria-hidden="true"></i><a href="mailto:info@example.com">info@example.com</a></li>
					<li><i class="fa fa-phone" aria-hidden="true"></i>+09187 8088 9436</li>
				</ul>
			</div>
			<div class="clearfix"> </div>
			<div class="footer_grids">
				<div class="col-md-4 footer_grid_left">
					<h3>Sign up for our Newsletter</h3>
				</div>
				<div class="col-md-8 footer_grid_right">

					<form action="#" method="post">
						<input type="email" name="Email" placeholder="Enter Email Address..." required="">
						<input type="submit" value="Submit">
					</form>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<div class="footer_w3ls">
		<div class="container">
					<div class="footer_bottom1">
						<p>© 2018 Instruction. All rights reserved | Design by <a href="http://w3layouts.com">W3layouts</a></p>
					</div>
		</div>
	</div>
	<!-- //footer -->

    <a href="#home" class="scroll" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
	<!-- js -->
	
	<script type="text/javascript" src="../../js/bootstrap.js"></script>
	<!-- stats -->
	<script src="../../js/jquery.waypoints.min.js"></script>
	<script src="../../js/jquery.countup.js"></script>
	<script>
	    $('.counter').countUp();
	</script>
	<!-- //stats -->
	<!-- owl carousel -->
	<script src="../../js/owl.carousel.js"></script>
	<script>
	    $(document).ready(function () {
	        $("#owl-demo").owlCarousel({

	            autoPlay: 3000, //Set AutoPlay to 3 seconds
	            autoPlay: true,
	            items: 3,
	            itemsDesktop: [991, 2],
	            itemsDesktopSmall: [414, 4]

	        });
	    }); 
	</script>
	<!-- //owl carousel -->

</body>
</html>